<?php
//Autor: Sergio Loyola www.serloy.com.ar
$labels = array();
$labels['shownotifies'] = 'Notificaciones Escritorio';
$labels['onlynew'] = 'Mostrar sólo los mensajes nuevos';
$labels['conf_browser'] = 'Configurar Navegador';
$labels['test_browser'] = 'Prueba';
$labels['excluded_directories'] = 'Directorios excluido de notificaciones';
$labels['check_ok'] = 'La configuración de tu Navegador es correcta.';
$labels['check_fail'] = 'No fue posible mostrar la notificación, por favor haz clic en "Configurar Navegador"!';
$labels['check_fail_blocked'] = 'Su navegador bloqueó la notificación, por favor, establezca el permiso en la configuración del navegador!';
$labels['no_notifications'] = 'Su Navegador no permite nofitificaciones!';
$labels['ok_notifications'] = 'Esta web ya tiene permiso. Las notificaciones por Escritorio deberían de estar funcionando.';
$labels['notification_title'] = 'Nuevo Email de [from]';

$labels['seconds'] = 'segundos';
$labels['off'] = 'desactivado';
$labels['durable'] = 'durable';

$labels['no_mailbox'] = 'no mostrar bandeja';
$labels['short_mailbox'] = 'mostrar un extracto de bandeja';
$labels['full_mailbox'] = 'mostrar toda la bandeja';

$labels['notifier_popuptype'] = 'Cómo abrir el mensaje en la notificación';
$labels['new_tab'] = 'En una pestaña nueva';
$labels['new_window'] = 'En una ventana nueva';



?>
